name: tests-backend

on:
  pull_request:
    paths:
      - "aio-back/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd aio-back && npm install && npm run test:ci
